### ISSUE TITLE
Elle vous plait pas la fin ?

### ISSUE THREAD

**Issue by Vlequay** [PolytechLyon/4a-isi3-tp3-2016-2017-groupe-2-diab-piat#1]
Il y a un soucis sur les dernières questions ? (vous pouvez zapper la 9)

**Comment by GregoirePiat** [comment]
J'avais oublié que nous n'avions pas fini ce TP. Je m'en occupe aujourd'hui et je ferme l'issue dès que le TP est fini.

**Comment by GregoirePiat** [comment]
J'ai répondu aux questions 8 et 10, j'ai essayé de faire la 9 mais EMMA ne fonctionne pas sous IntelliJ avec Java 8.

**Comment by Vlequay** [comment]
Ya un outil intégré à IntelliJ qui marche plus ou moins mais pas la peine de se prendre la tête.
